//Taylor Zweigle, 2023
import * as RefTokens from "./referenceTokens";

/*****DEFAULT*****/
export const SYS_COMMON_BLACK = RefTokens.REF_BLACK;
export const SYS_COMMON_WHITE = RefTokens.REF_WHITE;
export const SYS_GRAY_50 = RefTokens.REF_GRAY_50;
export const SYS_GRAY_100 = RefTokens.REF_GRAY_100;
export const SYS_GRAY_200 = RefTokens.REF_GRAY_200;
export const SYS_GRAY_300 = RefTokens.REF_GRAY_300;
export const SYS_GRAY_400 = RefTokens.REF_GRAY_400;
export const SYS_GRAY_500 = RefTokens.REF_GRAY_500;
export const SYS_GRAY_600 = RefTokens.REF_GRAY_600;
export const SYS_GRAY_700 = RefTokens.REF_GRAY_700;
export const SYS_GRAY_800 = RefTokens.REF_GRAY_800;
export const SYS_GRAY_900 = RefTokens.REF_GRAY_900;
export const SYS_ICON_SM = RefTokens.REF_ICON_SM;
export const SYS_ICON_MD = RefTokens.REF_ICON_MD;
export const SYS_ICON_LG = RefTokens.REF_ICON_LG;
export const SYS_ICON_XL = RefTokens.REF_ICON_XL;
export const SYS_TEXT_TRANSFORM = RefTokens.TEXT_TRANSFORM;

/*****LIGHT THEME*****/
export const SYS_LIGHT_THEME_PRIMARY_MAIN = RefTokens.REF_BLUE_50;
export const SYS_LIGHT_THEME_PRIMARY_LIGHT = RefTokens.REF_BLUE_95;
export const SYS_LIGHT_THEME_PRIMARY_DARK = RefTokens.REF_BLUE_40;
export const SYS_LIGHT_THEME_SECONDARY_MAIN =
  RefTokens.REF_LIGHT_THEME_GREEN_400;
export const SYS_LIGHT_THEME_SECONDARY_LIGHT =
  RefTokens.REF_LIGHT_THEME_GREEN_50;
export const SYS_LIGHT_THEME_SECONDARY_DARK =
  RefTokens.REF_LIGHT_THEME_GREEN_700;
export const SYS_LIGHT_THEME_TERTIARY_MAIN = RefTokens.REF_LIGHT_THEME_RED_400;
export const SYS_LIGHT_THEME_TERTIARY_LIGHT = RefTokens.REF_LIGHT_THEME_RED_50;
export const SYS_LIGHT_THEME_TERTIARY_DARK = RefTokens.REF_LIGHT_THEME_RED_700;
export const SYS_LIGHT_THEME_ERROR_MAIN = RefTokens.REF_LIGHT_THEME_RED_400;
export const SYS_LIGHT_THEME_ERROR_LIGHT = RefTokens.REF_LIGHT_THEME_RED_100;
export const SYS_LIGHT_THEME_ERROR_DARK = RefTokens.REF_LIGHT_THEME_RED_700;
export const SYS_LIGHT_THEME_WARNING_MAIN =
  RefTokens.REF_LIGHT_THEME_ORANGE_400;
export const SYS_LIGHT_THEME_WARNING_LIGHT =
  RefTokens.REF_LIGHT_THEME_ORANGE_100;
export const SYS_LIGHT_THEME_WARNING_DARK =
  RefTokens.REF_LIGHT_THEME_ORANGE_700;
export const SYS_LIGHT_THEME_INFO_MAIN = RefTokens.REF_BLUE_50;
export const SYS_LIGHT_THEME_INFO_LIGHT = RefTokens.REF_BLUE_95;
export const SYS_LIGHT_THEME_INFO_DARK = RefTokens.REF_BLUE_40;
export const SYS_LIGHT_THEME_SUCCESS_MAIN = RefTokens.REF_LIGHT_THEME_GREEN_400;
export const SYS_LIGHT_THEME_SUCCESS_LIGHT =
  RefTokens.REF_LIGHT_THEME_GREEN_100;
export const SYS_LIGHT_THEME_SUCCESS_DARK = RefTokens.REF_LIGHT_THEME_GREEN_700;

export const SYS_LIGHT_THEME_CHART_50 = RefTokens.REF_BLUE_95;
export const SYS_LIGHT_THEME_CHART_100 = RefTokens.REF_BLUE_85;
export const SYS_LIGHT_THEME_CHART_200 = RefTokens.REF_BLUE_75;
export const SYS_LIGHT_THEME_CHART_300 = RefTokens.REF_BLUE_65;
export const SYS_LIGHT_THEME_CHART_400 = RefTokens.REF_BLUE_55;
export const SYS_LIGHT_THEME_CHART_500 = RefTokens.REF_BLUE_45;
export const SYS_LIGHT_THEME_CHART_600 = RefTokens.REF_BLUE_35;
export const SYS_LIGHT_THEME_CHART_700 = RefTokens.REF_BLUE_25;
export const SYS_LIGHT_THEME_CHART_800 = RefTokens.REF_BLUE_15;
export const SYS_LIGHT_THEME_CHART_900 = RefTokens.REF_BLUE_05;

export const SYS_LIGHT_THEME_TEXT_PRIMARY =
  RefTokens.REF_LIGHT_THEME_TEXT_PRIMARY;
export const SYS_LIGHT_THEME_TEXT_SECONDARY =
  RefTokens.REF_LIGHT_THEME_TEXT_SECONDARY;
export const SYS_LIGHT_THEME_TEXT_DISABLED =
  RefTokens.REF_LIGHT_THEME_TEXT_DISABLED;

export const SYS_LIGHT_THEME_BACKGROUND_PAPER = RefTokens.REF_WHITE;
export const SYS_LIGHT_THEME_BACKGROUND_DEFAULT = RefTokens.REF_WHITE;

/*****DARK THEME*****/
export const SYS_DARK_THEME_PRIMARY_MAIN = RefTokens.REF_BLUE_50;
export const SYS_DARK_THEME_PRIMARY_LIGHT = RefTokens.REF_BLUE_40;
export const SYS_DARK_THEME_PRIMARY_DARK = RefTokens.REF_BLUE_95;
export const SYS_DARK_THEME_SECONDARY_MAIN = RefTokens.REF_DARK_THEME_GREEN_400;
export const SYS_DARK_THEME_SECONDARY_LIGHT =
  RefTokens.REF_DARK_THEME_GREEN_700;
export const SYS_DARK_THEME_SECONDARY_DARK = RefTokens.REF_DARK_THEME_GREEN_100;
export const SYS_DARK_THEME_TERTIARY_MAIN = RefTokens.REF_DARK_THEME_RED_400;
export const SYS_DARK_THEME_TERTIARY_LIGHT = RefTokens.REF_DARK_THEME_RED_700;
export const SYS_DARK_THEME_TERTIARY_DARK = RefTokens.REF_DARK_THEME_RED_100;
export const SYS_DARK_THEME_ERROR_MAIN = RefTokens.REF_DARK_THEME_RED_400;
export const SYS_DARK_THEME_ERROR_LIGHT = RefTokens.REF_DARK_THEME_RED_100;
export const SYS_DARK_THEME_ERROR_DARK = RefTokens.REF_DARK_THEME_RED_700;
export const SYS_DARK_THEME_WARNING_MAIN = RefTokens.REF_DARK_THEME_ORANGE_400;
export const SYS_DARK_THEME_WARNING_LIGHT = RefTokens.REF_DARK_THEME_ORANGE_100;
export const SYS_DARK_THEME_WARNING_DARK = RefTokens.REF_DARK_THEME_ORANGE_700;
export const SYS_DARK_THEME_INFO_MAIN = RefTokens.REF_BLUE_50;
export const SYS_DARK_THEME_INFO_LIGHT = RefTokens.REF_BLUE_40;
export const SYS_DARK_THEME_INFO_DARK = RefTokens.REF_BLUE_95;
export const SYS_DARK_THEME_SUCCESS_MAIN = RefTokens.REF_DARK_THEME_GREEN_400;
export const SYS_DARK_THEME_SUCCESS_LIGHT = RefTokens.REF_DARK_THEME_GREEN_100;
export const SYS_DARK_THEME_SUCCESS_DARK = RefTokens.REF_DARK_THEME_GREEN_700;

export const SYS_DARK_THEME_CHART_50 = RefTokens.REF_BLUE_100;
export const SYS_DARK_THEME_CHART_100 = RefTokens.REF_BLUE_95;
export const SYS_DARK_THEME_CHART_200 = RefTokens.REF_BLUE_90;
export const SYS_DARK_THEME_CHART_300 = RefTokens.REF_BLUE_85;
export const SYS_DARK_THEME_CHART_400 = RefTokens.REF_BLUE_80;
export const SYS_DARK_THEME_CHART_500 = RefTokens.REF_BLUE_75;
export const SYS_DARK_THEME_CHART_600 = RefTokens.REF_BLUE_70;
export const SYS_DARK_THEME_CHART_700 = RefTokens.REF_BLUE_65;
export const SYS_DARK_THEME_CHART_800 = RefTokens.REF_BLUE_60;
export const SYS_DARK_THEME_CHART_900 = RefTokens.REF_BLUE_55;

export const SYS_DARK_THEME_TEXT_PRIMARY =
  RefTokens.REF_DARK_THEME_TEXT_PRIMARY;
export const SYS_DARK_THEME_TEXT_SECONDARY =
  RefTokens.REF_DARK_THEME_TEXT_SECONDARY;
export const SYS_DARK_THEME_TEXT_DISABLED =
  RefTokens.REF_DARK_THEME_TEXT_DISABLED;

export const SYS_DARK_THEME_BACKGROUND_PAPER = RefTokens.REF_BLACK;
export const SYS_DARK_THEME_BACKGROUND_DEFAULT = RefTokens.REF_BLACK;
